spring:
  application:
    name: driveme-backend
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:5433/driveme}
    username: ${SPRING_DATASOURCE_USERNAME:driveme}
    password: ${SPRING_DATASOURCE_PASSWORD:driveme123}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    url: ${SPRING_FLYWAY_URL:${SPRING_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:5433/driveme}}
    user: ${SPRING_FLYWAY_USER:${SPRING_DATASOURCE_USERNAME:driveme}}
    password: ${SPRING_FLYWAY_PASSWORD:${SPRING_DATASOURCE_PASSWORD:driveme123}}

logging:
  level:
    root: INFO
    com.driveme.backend: INFO